### ISSUE TITLE
Swapping out env: with with: should fix this error. 

### ISSUE THREAD

**Issue by XiaoXice** [paxyqi/mahjong#1]
https://github.com/paxyqi/mahjong/blob/7d60630416216dc763292544f6f0a1269c6f0f77/.github/workflows/ci.yml#L37

https://github.com/JamesIves/github-pages-deploy-action/issues/355

**Comment by Gaojianli** [comment]
https://github.com/JamesIves/github-pages-deploy-action/issues/355#issuecomment-654203686

**Comment by XiaoXice** [comment]
Congratulation!
