### ISSUE TITLE
Got Incorrect Syanten Result

### ISSUE THREAD

**Issue by Jasonxia007** [paxyqi/mahjong#6]
input: `6777888p2367s11z`
got result: `3向聴`
should be: `1向聴`
in this case, draw 1/4/5/8s then discard 6p gets a Ready Hand/ richii.

**Comment by paxyqi** [comment]
Thank you for your report, I`ll check it.

**Comment by paxyqi** [comment]
This bug will happen when the input looks like 6777888. Because I calculate the _tatsu_ first, like calculate the 678 as a _tatsu_, then the 77&88will be left, but not calculate the 777&888 as two _mentsu_.  I`ll fix it soon.

**Comment by paxyqi** [comment]
**Fix it**, plz try. Thank you for your report again.
